name = "jav-manager-telemetry"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "jav-manager"
database_id = "db53e6b2-5ef3-4631-930f-5ee09059f6d5"
