name = "jav-manager-telemetry"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "small-projects"
database_id = "f410db86-56a3-42db-8685-f3fcab051e19"
